[
    { 'ID': 31, 'Amount': 52, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Prévision', 'Year': '2019', 'Month': 'Mois 01', 'Semaine': 'Semaine 1' },
    { 'ID': 31, 'Amount': 20, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Prévision', 'Year': '2019', 'Month': 'Mois 01', 'Semaine': 'Semaine 2' },
    { 'ID': 31, 'Amount': 32, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Prévision', 'Year': '2019', 'Month': 'Mois 01', 'Semaine': 'Semaine 3' },
    { 'ID': 31, 'Amount': 14, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Prévision', 'Year': '2019', 'Month': 'Mois 01', 'Semaine': 'Semaine 4' },
    { 'ID': 31, 'Amount': 2, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Stock', 'Year': '2019', 'Month': 'Mois 01', 'Semaine': 'Semaine 1' },
    { 'ID': 31, 'Amount': 0, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Stock', 'Year': '2019', 'Month': 'Mois 01', 'Semaine': 'Semaine 2' },
    { 'ID': 31, 'Amount': 0, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Stock', 'Year': '2019', 'Month': 'Mois 01', 'Semaine': 'Semaine 3' },
    { 'ID': 31, 'Amount': 0, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Stock', 'Year': '2019', 'Month': 'Mois 01', 'Semaine': 'Semaine 4' },

    { 'ID': 31, 'Amount': 52, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Prévision', 'Year': '2019', 'Month': 'Mois 02', 'Semaine': 'Semaine 1' },
    { 'ID': 31, 'Amount': 20, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Prévision', 'Year': '2019', 'Month': 'Mois 02', 'Semaine': 'Semaine 2' },
    { 'ID': 31, 'Amount': 32, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Prévision', 'Year': '2019', 'Month': 'Mois 02', 'Semaine': 'Semaine 3' },
    { 'ID': 31, 'Amount': 14, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Prévision', 'Year': '2019', 'Month': 'Mois 02', 'Semaine': 'Semaine 4' },
    { 'ID': 31, 'Amount': 2, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Stock', 'Year': '2019', 'Month': 'Mois 02', 'Semaine': 'Semaine 1' },
    { 'ID': 31, 'Amount': 0, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Stock', 'Year': '2019', 'Month': 'Mois 02', 'Semaine': 'Semaine 2' },
    { 'ID': 31, 'Amount': 0, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Stock', 'Year': '2019', 'Month': 'Mois 02', 'Semaine': 'Semaine 3' },
    { 'ID': 31, 'Amount': 0, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Stock', 'Year': '2019', 'Month': 'Mois 02', 'Semaine': 'Semaine 4' },

    { 'ID': 31, 'Amount': 52, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Prévision', 'Year': '2019', 'Month': 'Mois 03', 'Semaine': 'Semaine 1' },
    { 'ID': 31, 'Amount': 20, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Prévision', 'Year': '2019', 'Month': 'Mois 03', 'Semaine': 'Semaine 2' },
    { 'ID': 31, 'Amount': 32, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Prévision', 'Year': '2019', 'Month': 'Mois 03', 'Semaine': 'Semaine 3' },
    { 'ID': 31, 'Amount': 14, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Prévision', 'Year': '2019', 'Month': 'Mois 03', 'Semaine': 'Semaine 4' },
    { 'ID': 31, 'Amount': 2, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Stock', 'Year': '2019', 'Month': 'Mois 03', 'Semaine': 'Semaine 1' },
    { 'ID': 31, 'Amount': 0, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Stock', 'Year': '2019', 'Month': 'Mois 03', 'Semaine': 'Semaine 2' },
    { 'ID': 31, 'Amount': 0, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Stock', 'Year': '2019', 'Month': 'Mois 03', 'Semaine': 'Semaine 3' },
    { 'ID': 31, 'Amount': 0, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Stock', 'Year': '2019', 'Month': 'Mois 03', 'Semaine': 'Semaine 4' },

    { 'ID': 31, 'Amount': 52, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Prévision', 'Year': '2019', 'Month': 'Mois 04', 'Semaine': 'Semaine 1' },
    { 'ID': 31, 'Amount': 20, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Prévision', 'Year': '2019', 'Month': 'Mois 04', 'Semaine': 'Semaine 2' },
    { 'ID': 31, 'Amount': 32, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Prévision', 'Year': '2019', 'Month': 'Mois 04', 'Semaine': 'Semaine 3' },
    { 'ID': 31, 'Amount': 14, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Prévision', 'Year': '2019', 'Month': 'Mois 04', 'Semaine': 'Semaine 4' },
    { 'ID': 31, 'Amount': 2, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Stock', 'Year': '2019', 'Month': 'Mois 04', 'Semaine': 'Semaine 1' },
    { 'ID': 31, 'Amount': 0, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Stock', 'Year': '2019', 'Month': 'Mois 04', 'Semaine': 'Semaine 2' },
    { 'ID': 31, 'Amount': 0, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Stock', 'Year': '2019', 'Month': 'Mois 04', 'Semaine': 'Semaine 3' },
    { 'ID': 31, 'Amount': 0, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Stock', 'Year': '2019', 'Month': 'Mois 04', 'Semaine': 'Semaine 4' },

    { 'ID': 31, 'Amount': 52, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Prévision', 'Year': '2019', 'Month': 'Mois 05', 'Semaine': 'Semaine 1' },
    { 'ID': 31, 'Amount': 20, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Prévision', 'Year': '2019', 'Month': 'Mois 05', 'Semaine': 'Semaine 2' },
    { 'ID': 31, 'Amount': 32, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Prévision', 'Year': '2019', 'Month': 'Mois 05', 'Semaine': 'Semaine 3' },
    { 'ID': 31, 'Amount': 14, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Prévision', 'Year': '2019', 'Month': 'Mois 05', 'Semaine': 'Semaine 4' },
    { 'ID': 31, 'Amount': 2, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Stock', 'Year': '2019', 'Month': 'Mois 05', 'Semaine': 'Semaine 1' },
    { 'ID': 31, 'Amount': 0, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Stock', 'Year': '2019', 'Month': 'Mois 05', 'Semaine': 'Semaine 2' },
    { 'ID': 31, 'Amount': 0, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Stock', 'Year': '2019', 'Month': 'Mois 05', 'Semaine': 'Semaine 3' },
    { 'ID': 31, 'Amount': 0, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Stock', 'Year': '2019', 'Month': 'Mois 05', 'Semaine': 'Semaine 4' },

    { 'ID': 31, 'Amount': 52, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Prévision', 'Year': '2019', 'Month': 'Mois 06', 'Semaine': 'Semaine 1' },
    { 'ID': 31, 'Amount': 20, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Prévision', 'Year': '2019', 'Month': 'Mois 06', 'Semaine': 'Semaine 2' },
    { 'ID': 31, 'Amount': 32, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Prévision', 'Year': '2019', 'Month': 'Mois 06', 'Semaine': 'Semaine 3' },
    { 'ID': 31, 'Amount': 14, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Prévision', 'Year': '2019', 'Month': 'Mois 06', 'Semaine': 'Semaine 4' },
    { 'ID': 31, 'Amount': 2, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Stock', 'Year': '2019', 'Month': 'Mois 06', 'Semaine': 'Semaine 1' },
    { 'ID': 31, 'Amount': 0, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Stock', 'Year': '2019', 'Month': 'Mois 06', 'Semaine': 'Semaine 2' },
    { 'ID': 31, 'Amount': 0, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Stock', 'Year': '2019', 'Month': 'Mois 06', 'Semaine': 'Semaine 3' },
    { 'ID': 31, 'Amount': 0, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Stock', 'Year': '2019', 'Month': 'Mois 06', 'Semaine': 'Semaine 4' },

    { 'ID': 31, 'Amount': 52, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Prévision', 'Year': '2019', 'Month': 'Mois 07', 'Semaine': 'Semaine 1' },
    { 'ID': 31, 'Amount': 20, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Prévision', 'Year': '2019', 'Month': 'Mois 07', 'Semaine': 'Semaine 2' },
    { 'ID': 31, 'Amount': 32, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Prévision', 'Year': '2019', 'Month': 'Mois 07', 'Semaine': 'Semaine 3' },
    { 'ID': 31, 'Amount': 14, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Prévision', 'Year': '2019', 'Month': 'Mois 07', 'Semaine': 'Semaine 4' },
    { 'ID': 31, 'Amount': 2, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Stock', 'Year': '2019', 'Month': 'Mois 07', 'Semaine': 'Semaine 1' },
    { 'ID': 31, 'Amount': 0, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Stock', 'Year': '2019', 'Month': 'Mois 07', 'Semaine': 'Semaine 2' },
    { 'ID': 31, 'Amount': 0, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Stock', 'Year': '2019', 'Month': 'Mois 07', 'Semaine': 'Semaine 3' },
    { 'ID': 31, 'Amount': 0, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Stock', 'Year': '2019', 'Month': 'Mois 07', 'Semaine': 'Semaine 4' },

    { 'ID': 31, 'Amount': 52, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Prévision', 'Year': '2019', 'Month': 'Mois 08', 'Semaine': 'Semaine 1' },
    { 'ID': 31, 'Amount': 20, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Prévision', 'Year': '2019', 'Month': 'Mois 08', 'Semaine': 'Semaine 2' },
    { 'ID': 31, 'Amount': 32, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Prévision', 'Year': '2019', 'Month': 'Mois 08', 'Semaine': 'Semaine 3' },
    { 'ID': 31, 'Amount': 14, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Prévision', 'Year': '2019', 'Month': 'Mois 08', 'Semaine': 'Semaine 4' },
    { 'ID': 31, 'Amount': 2, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Stock', 'Year': '2019', 'Month': 'Mois 08', 'Semaine': 'Semaine 1' },
    { 'ID': 31, 'Amount': 0, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Stock', 'Year': '2019', 'Month': 'Mois 08', 'Semaine': 'Semaine 2' },
    { 'ID': 31, 'Amount': 0, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Stock', 'Year': '2019', 'Month': 'Mois 08', 'Semaine': 'Semaine 3' },
    { 'ID': 31, 'Amount': 0, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Stock', 'Year': '2019', 'Month': 'Mois 08', 'Semaine': 'Semaine 4' },

    { 'ID': 31, 'Amount': 52, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Prévision', 'Year': '2019', 'Month': 'Mois 09', 'Semaine': 'Semaine 1' },
    { 'ID': 31, 'Amount': 20, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Prévision', 'Year': '2019', 'Month': 'Mois 09', 'Semaine': 'Semaine 2' },
    { 'ID': 31, 'Amount': 32, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Prévision', 'Year': '2019', 'Month': 'Mois 09', 'Semaine': 'Semaine 3' },
    { 'ID': 31, 'Amount': 14, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Prévision', 'Year': '2019', 'Month': 'Mois 09', 'Semaine': 'Semaine 4' },
    { 'ID': 31, 'Amount': 2, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Stock', 'Year': '2019', 'Month': 'Mois 09', 'Semaine': 'Semaine 1' },
    { 'ID': 31, 'Amount': 0, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Stock', 'Year': '2019', 'Month': 'Mois 09', 'Semaine': 'Semaine 2' },
    { 'ID': 31, 'Amount': 0, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Stock', 'Year': '2019', 'Month': 'Mois 09', 'Semaine': 'Semaine 3' },
    { 'ID': 31, 'Amount': 0, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Stock', 'Year': '2019', 'Month': 'Mois 09', 'Semaine': 'Semaine 4' },

    { 'ID': 31, 'Amount': 52, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Prévision', 'Year': '2019', 'Month': 'Mois 10', 'Semaine': 'Semaine 1' },
    { 'ID': 31, 'Amount': 20, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Prévision', 'Year': '2019', 'Month': 'Mois 10', 'Semaine': 'Semaine 2' },
    { 'ID': 31, 'Amount': 32, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Prévision', 'Year': '2019', 'Month': 'Mois 10', 'Semaine': 'Semaine 3' },
    { 'ID': 31, 'Amount': 14, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Prévision', 'Year': '2019', 'Month': 'Mois 10', 'Semaine': 'Semaine 4' },
    { 'ID': 31, 'Amount': 2, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Stock', 'Year': '2019', 'Month': 'Mois 10', 'Semaine': 'Semaine 1' },
    { 'ID': 31, 'Amount': 0, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Stock', 'Year': '2019', 'Month': 'Mois 10', 'Semaine': 'Semaine 2' },
    { 'ID': 31, 'Amount': 0, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Stock', 'Year': '2019', 'Month': 'Mois 10', 'Semaine': 'Semaine 3' },
    { 'ID': 31, 'Amount': 0, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Stock', 'Year': '2019', 'Month': 'Mois 10', 'Semaine': 'Semaine 4' },

    { 'ID': 31, 'Amount': 52, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Prévision', 'Year': '2019', 'Month': 'Mois 11', 'Semaine': 'Semaine 1' },
    { 'ID': 31, 'Amount': 20, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Prévision', 'Year': '2019', 'Month': 'Mois 11', 'Semaine': 'Semaine 2' },
    { 'ID': 31, 'Amount': 32, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Prévision', 'Year': '2019', 'Month': 'Mois 11', 'Semaine': 'Semaine 3' },
    { 'ID': 31, 'Amount': 14, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Prévision', 'Year': '2019', 'Month': 'Mois 11', 'Semaine': 'Semaine 4' },
    { 'ID': 31, 'Amount': 2, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Stock', 'Year': '2019', 'Month': 'Mois 11', 'Semaine': 'Semaine 1' },
    { 'ID': 31, 'Amount': 0, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Stock', 'Year': '2019', 'Month': 'Mois 11', 'Semaine': 'Semaine 2' },
    { 'ID': 31, 'Amount': 0, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Stock', 'Year': '2019', 'Month': 'Mois 11', 'Semaine': 'Semaine 3' },
    { 'ID': 31, 'Amount': 0, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Stock', 'Year': '2019', 'Month': 'Mois 11', 'Semaine': 'Semaine 4' },

    { 'ID': 31, 'Amount': 52, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Prévision', 'Year': '2019', 'Month': 'Mois 12', 'Semaine': 'Semaine 1' },
    { 'ID': 31, 'Amount': 20, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Prévision', 'Year': '2019', 'Month': 'Mois 12', 'Semaine': 'Semaine 2' },
    { 'ID': 31, 'Amount': 32, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Prévision', 'Year': '2019', 'Month': 'Mois 12', 'Semaine': 'Semaine 3' },
    { 'ID': 31, 'Amount': 14, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Prévision', 'Year': '2019', 'Month': 'Mois 12', 'Semaine': 'Semaine 4' },
    { 'ID': 31, 'Amount': 2, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Stock', 'Year': '2019', 'Month': 'Mois 12', 'Semaine': 'Semaine 1' },
    { 'ID': 31, 'Amount': 0, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Stock', 'Year': '2019', 'Month': 'Mois 12', 'Semaine': 'Semaine 2' },
    { 'ID': 31, 'Amount': 0, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Stock', 'Year': '2019', 'Month': 'Mois 12', 'Semaine': 'Semaine 3' },
    { 'ID': 31, 'Amount': 0, 'Article': 'MOTEUR DIESEL 170F', 'TypeParams': 'Stock', 'Year': '2019', 'Month': 'Mois 12', 'Semaine': 'Semaine 4' },
  ];